### ISSUE TITLE
RestClient handle thread safe

### ISSUE THREAD

**Issue by lathakris** [EMCECS/rest-client-c#3]
Hi,
Is  the handle created using RestClient_init() thead safe ? Can I use the same RestClient handle across threads within a process. I read that it should be fine as long as it is compiled using pthread, I assume that is the default compile option.

Thanks.

**Comment by jasoncwik** [comment]
So, I was looking at this and it appears that pthread support might be broken.  This code was originally developed to run on an appliance whose build system defined _PTHREADS for builds that used threading.  It appears that the proper flag is really _REENTRANT and is defined by passing -pthread to gcc on compile and link.  I tried defining that and it appears there's some compile errors in gcc now.

**Comment by jasoncwik** [comment]
@lathakris please check out PR #4.  That should add proper pthread support (pthreads are now enabled by default).

**Comment by lathakris** [comment]
oh wow. that was very quick. Thank you so much for the fix. so would this fix merge into master ? Should I pull it from master after the merge ?

**Comment by jasoncwik** [comment]
Can you pull from my branch and test first in your environment?  If it looks good I can merge to master.  I might have to do some other testing here first as well with another product that uses it.

**Comment by lathakris** [comment]
ok Jason, I can do that. will keep you posted.

Thanks.

**Comment by lathakris** [comment]
I have done the testing from this branch, looks good. Please let me know the next steps..

**Comment by lathakris** [comment]
Hi Jason, any updates on this ? should I use this branch or will it merge to master ? Thanks.

**Comment by jasoncwik** [comment]
Hi Latha,

Joe Conery will merge the fix and issue a new release this week.

**Comment by lathakris** [comment]
Jason, thank you for the update, I will look out for the release.

**Comment by meetgrinder** [comment]
Test suite summary for version 1.0.2 passes and seems to resolve issue

**Comment by lathakris** [comment]
Thank you. should I pick a new build from master then ?

**Comment by jasoncwik** [comment]
Yes, or you can download the release tar

**Comment by lathakris** [comment]
thank you I have picked the release tar.
